Icinga/icingaweb2-module-cube

- README.md
> Docs: Add a note for PostgreSQL 9.5+ ROLLUP requirement

- application/forms/DimensionsForm.php
> Limit to 3 dimensions

- library/Cube/DbCube.php
- library/Cube/Dimension.php
- library/Cube/Ido/CustomVarDimension.php
> Fix identifier quoting

- library/Cube/Ido/IdoHostStatusCube.php
- library/Cube/Ido/IdoHostStatusCubeRenderer.php
- library/Cube/Ido/IdoServiceStatusCube.php
- library/Cube/Ido/IdoStatusCubeRenderer.php
- public/css/module.less
> Fix cube do not turn yellow for warning

- library/Cube/Ido/IdoHostStatusCube.php
- library/Cube/Ido/IdoServiceStatusCube.php
> Order custom var dimensions by name

- library/Cube/CubeRenderer.php
> Add context to the cube title tooltip

- library/Cube/Cube.php
> Replace depricated each() func with foreach loop

- module.info
> Update module version

- application/forms/DimensionsForm.php
- public/css/module.less
> Adjust less variable usage

- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
- library/Cube/IcingaDb/IcingaDbServiceStatusCube.php
Required due to https://github.com/Icinga/icingadb-web/pull/536/commits/854151f882a9dc575e8741259c5f03be159d4401
> Compatibility with Icinga DB Web 1.0.0 Stable

- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
- library/Cube/IcingaDb/IcingaDbServiceStatusCube.php
Required due to https://github.com/Icinga/ipl-orm/pull/62
> Compatibility with ipl-orm v0.4.0

- library/Cube/IcingaDb/CustomVariableDimension.php
- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
- library/Cube/IcingaDb/IcingaDbServiceStatusCube.php
> icingadb: Suggest and handle array variables differently

- .gitattributes
Remove phpcs.xml and Git-related files from archives.
> Export ignore

- library/Cube/Cube.php
- library/Cube/IcingaDb/CustomVariableDimension.php
- library/Cube/IcingaDb/IcingaDbCube.php
- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
- library/Cube/IcingaDb/IcingaDbServiceStatusCube.php
- library/Cube/Ido/IdoHostStatusCube.php
- library/Cube/Ido/IdoServiceStatusCube.php
- library/Cube/ProvidedHook/Cube/IcingaDbActions.php
> Allows grouping of services according to host custom variables

- application/controllers/HostsController.php
- application/controllers/IdoHostsController.php
- application/controllers/IdoServicesController.php
- application/controllers/ServicesController.php
- application/forms/DimensionsForm.php
- application/views/scripts/cube-details.phtml
- application/views/scripts/cube-index.phtml
- library/Cube/Cube.php
- library/Cube/CubeRenderer.php
- library/Cube/CubeRenderer/HostStatusCubeRenderer.php
- library/Cube/CubeRenderer/ServiceStatusCubeRenderer.php
- library/Cube/IcingaDb/IcingaDbCube.php
- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
- library/Cube/IcingaDb/IcingaDbServiceStatusCube.php
- library/Cube/Ido/IdoCube.php
- library/Cube/ProvidedHook/Cube/IcingaDbActions.php
- library/Cube/Web/Controller.php
- library/Cube/Web/IdoController.php
- run.php
resolves #16 
- https://github.com/Icinga/icingaweb2-module-cube/pull/97
> IcingaDb Cube: Add filter and problem only controls

- library/Cube/CubeRenderer/HostStatusCubeRenderer.php
- library/Cube/CubeRenderer/ServiceStatusCubeRenderer.php
> Fix state color (css class) of outer dimension

- library/Cube/CubeRenderer/HostStatusCubeRenderer.php
- library/Cube/CubeRenderer/ServiceStatusCubeRenderer.php
| Priority | Old Order          | New Order          |
|----------|--------------------|--------------------|
| 1        | `critical`         | `critical`         |
| 2        | `critical handled` | `warning`          |
| 3        | `warning`          | `unknown`          |
| 4        | `warning handled`  | `critical handled` |
| 5        | `unknown`          | `unknown handled`  |
| 6        | `unknown handled`  | `warning handled`  |
| 7        | `ok`               | `ok`               |
| Priority | Old Order             | New Order             |
|----------|-----------------------|-----------------------|
| 1        | `critical`            | `critical`            |
| 2        | `critical handled`    | `unreachable`         |
| 3        | `unreachable`         | `critical handled`    | …
> Change severity order acording to icingadb

- library/Cube/CubeRenderer.php
- library/Cube/IcingaDb/IcingaDbCube.php
- library/Cube/ProvidedHook/Cube/IcingaDbActions.php
- library/Cube/Web/Controller.php
- public/css/module.less
> Fix cube details not filtered

- library/Cube/CubeRenderer.php
- library/Cube/CubeRenderer/HostStatusCubeRenderer.php
- library/Cube/CubeRenderer/ServiceStatusCubeRenderer.php
- library/Cube/IcingaDb/IcingaDbCube.php
- library/Cube/Web/Controller.php
- public/css/module.less
> IcingaDB cube: Add sort control

- public/css/module.less
> module.less: Fix action link layout

- library/Cube/Web/Controller.php
- library/Cube/Web/IdoController.php
> IdoController: Remove icingadb control params independently from current active tab

- application/forms/DimensionsForm.php
- library/Cube/Web/Controller.php
- library/Cube/Web/IdoController.php
- public/css/module.less
require https://github.com/Icinga/ipl-html/pull/116
This PR also fixes the problem that the search bar filters are deleted when adding, moving or removing dimensions.
> DimensionsForm: Use ipl-form

- library/Cube/Web/IdoController.php
> IdoController: Call icingadb related methods only if icingadb is enabled

- library/Cube/Web/Controller.php
- library/Cube/Web/IdoController.php
> Fix got no such dimension issue

- library/Cube/CubeRenderer/HostStatusCubeRenderer.php
- library/Cube/IcingaDb/IcingaDbHostStatusCube.php
> Drop IcingaDB `hosts_(unhandled)_unreachable` columns

- library/Cube/Web/Controller.php
- library/Cube/Web/IdoController.php
> Controllers: Don't pass `format` param to db query

- configuration.php
Both are synchronized with the monitoring and reporting module now. No matter which one is enabled, the section looks always the same.
> configuration.php: Define a icon and priority for the menu integration

- library/Cube/Web/Controller.php
Supported since ipl 0.12.0, mandatory with ipl 0.15.0.
> Controller: Call `SortControl::handleRequest()`
